<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - England</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="england.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>

<div id="overskriftfotball">
<h2>Fotball i Argentina</h2>
</div>
<img id="argentina" src="afa.jpg" alt="Argentina"/>
<img id="argentina2" src="afa.jpg" alt="Argentina"/>
<!-- Bildene er hentet fra Wikipedia http://en.wikipedia.org/wiki/File:Bombonera_Boca_Juniors.JPG, 
http://en.wikipedia.org/wiki/File:Superclasico-Monumental.jpg-->
<div id="textmidt">
<p>Argentinsk liga er en fartsfylt liga, med høyt tempo, høyt temprement, og mye liv på tribunene.</p>
<p>Oppgjørene mellom Boca Juniors, og River Plate er et skikkelig by-derby i Buenos Aires, hvor hele byen står på hodet på
kampdagen. Denne ligaen har hatt store spillere som, Diego Maradona, Pablo Aimar, Gabriel Batistuta, Hernan Crespo og Carlos Tevez, for å nevne noen.</p>
<p>I April 2004, lagde den engelske avisen The Observer en liste over <a href="http://observer.guardian.co.uk/osm/story/0,,1182710,00.html">50 sportsbegivenheter</a> du må få med deg før du dør, og kampen mellom
Boca Juniors og River Plate kom på førsteplass!</p>
<p>iTravel kan tilby deg en total pakke, med fly, kampbilletter, og hotell, på alle kampene i Argentina.</p>

</div>
<br/><br />
<img id="bildevenstre" src="boca.jpg" alt="Boca Juniors" /> 

<img id="bildehoyre" src="river.jpg" alt="River Plate" /> 
<div id="textboca"><p><em>Estadio Alberto J. Armando, Boca Juniors, i Buenos Aires, </em></p></div> 
<div id="textunderhoyre"><p><em>River Plate Stadium, Buenos Aires</em></p></div>
</div>


</div>

</body>
</html>