<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Australia</title>
</head>



<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="australiafisk.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="australiafisk.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="australiafisk.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="australiafisk.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="australiafisk.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>



<h2>Fisketur i Australia</h2>
<div id="sveits">
<p>Australia har veldig mange muligheter for en sportsfisker. Store fiskeområder med sjeldne fisk i ferskvann og saltvann, haier og kort sagt –
 all type fisk en sportsfisker kan ønske seg. Store og små, sterke og late, tunge og lette, ja hva du måtte ønske deg.   </p>
<p>Ferskvannsfiskene Barramundi og Flathead er svært populære for sportsfiskere grunnet deres fenomenale evne til å kjempe imot. Barramundien er
 i tillegg en veldig god matfisk.  </p> 
<p>Du kan fiske torsk på opp mot 60 kg ved Great Barrier Reef eller Giant Trevallies og Queenfish utenfor kysten i Northern Territories ute på 
båtene til våre samarbeidspartnere og oppleve sportsfiske slik man vanligvis kun får se på TV. 
</p>
<p>Vi tilbyr også kanskje det mest ekstreme sportsfisket man kan komme borti, nemlig fiske av Blue Marlin. Denne fisken regnes som toppen av
 sportsfiske på grunn av dens enorme størrelse, vanvittige styrke og det at den er relativt sjelden. Det største eksemplaret av Blue Marlin
 som er tatt, og som er offisielt godkjente, veide nesten 650 kilo. Det har også blitt tatt fisker opp mot 800kg, men disse er ikke blitt 
 godkjente som offisielle rekorder. Disse størrelsene, samt dens enestående styrke, sier vel alt om hvorfor mange regner Blue Marlin for 
 å være sportsfiskets svar på Formel-1. </p></div>
<img id="sveitsa" src="australiabarra.jpg" alt="Barramundi"/>
<img id="sveitsh" src="australiamarlin.png" alt="Marlin" />
<div id="sveitstekst"><p><em>En fantastiske ferskvannsfiskene, Barramundi</em></p></div> 
<div id="sveitstekst2"><p><em>Fiskenes Formel-1, en Marlin i aksjon</em></p></div>


<!--Kilder
http://www.wikipedia.com
http://www.angling-adventures.com.au

Bilde:
http://www.anglingadventures.com.au/media/images/47f3310376fcc_strip8_lg.jpg
http://upload.wikimedia.org/wikipedia/commons/d/d9/Marlin.png-->




</div>

</body>
</html>