<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>Australia</title>
</head>

<body background="paradis.jpg">

<div id="overbodybox">
<ul><li><a href="omoss.html" >Om oss</a></li> 
<li><a href="kontakt.html" >Kontakt oss</a></li>
<li><a href="reisevilkar.html" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<h1 id="overskrift">Australia</h1>
<table id="menytabell">
<form action="" method="get">
<tr>
<td><a id="hjemknapp" href="index.phtml">Hjem</a></td>
<td><input class="meny" type="submit" value="  Fisketur  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferie  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballtur " name="fotball"/></td>
</tr>
</form>


<?php

if (isset($_REQUEST["fisk"]))
{
     $_SESSION["filnavn"]="australia.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
    $_SESSION["filnavn"]="australia.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
    $_SESSION["filnavn"]="australia.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="australia.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>






<img id="Bali" src="bali.jpg" alt="Bali"   /> 
<img id="Berlin"  src="berlin.jpg" alt="Berlin"  />

<p>Australia, en hver surfers paradis!</p>
</div>

</body>
</html>