<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Bali</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="england.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>

<div id="overskriftfotball">
<h2>Surfing på Bali</h2>
</div>


<div id="textmidt">

<p>Bali er en eksotisk øy i Indonesia med nydelig natur, og tropisk klima. På Bali kan du oppleve alt du ønsker, fra Safari til yrende uteliv</p>
<p>Surfing og Bali går som hånd i hanske, da det er varmt i vannet, og havet kan tilby alt fra små dønninger, til over 10 meter høye bølger.
Temperaturen i vannet er rundt 30 grader, noe som gjør at man kan være lenge i vannet, uten å måtte bekymre seg for å bli kald. </p>
<p>Hvis man drar til Bali for å lære og surfe, finnes det mange forskjellige surfeskoler man kan dra til. Dette er en rimelig invistering før 
man begir seg ut på bølgan den blå.</p>
</div>
<br/><br />
<img id="bildevenstre" src="dreamland.jpg" alt="Dreamland beach, Bali" /> 
<img id="bildehoyre" src="balisurf.2.jpg" alt="Surfing på Bali" /> 
<div id="textundervenstre"><p><em>Dreamland Beach</em></p></div> 
<div id="textunderhoyre"><p><em>Surfing på Kuta Beach</em></p></div>
</div>


</div>

</body>
</html>