<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
<link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />

</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.html" >Om oss</a></li> 
<li><a href="kontakt.html" >Kontakt oss</a></li>
<li><a href="reisevilkar.html" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<div id="meny">
<ul>
<li><strong><a style="background: #CCC;" href="index.phtml">Hjem</a></strong></li>
</ul>
<ul>
<li><a href="#">Fisketurer</a>
<ul>
<li><a href="lofoten.html">Lofoten</a></li>
<li><a href="florida.html">Florida</a></li>
<li><a href="australiafisk.html">Australia</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#">Surfing</a>
<ul>
<li><a href="bali.html">Bali</a></li>
<li><a href="australia.html">Australia</a></li>
<li><a href="hawaii.html">Hawaii</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#">Skiferie</a>
<ul>
<li><a href="sveits.html">Sveits</a></li>
<li><a href="usa.html">USA</a></li>
<li><a href="italia.html">Italia</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#">Fotballtur</a>
<ul>
<li><a href="england.html">England</a></li>
<li><a href="spania.html">Spania</a></li>
<li><a href="argentina.html">Argentina</a></li>
</ul>
</li>
</ul>


</div>
</div>


<br/><br/>
<p>Er du lei av allminnelige reisemål der du bare ligger og kjeder deg på stranda hele ferien? 
Ønsker du å gjøre noe nytt i ferien? iTravel arrangerer reiser for den mer eventyrlystne som ønsker
 å oppleve mer i ferien. Velkommen til iTravel - vi er her for deg!</p>
<img id="balisurf" src="balisurf.png" alt="bali" />

<div id="bestillher">
<h3>Bestill her!</h3>
</div>
<div id="bestilling1">
<?php
if($_REQUEST["dag"] =="" or $_REQUEST["dato"] =="" or $_REQUEST["aar"] =="" or $_REQUEST["daghjem"] =="" or $_REQUEST["datohjem"] =="" or $_REQUEST["aarhjem"] =="") 
{
	echo "Du har ikke fylt ut all informasjonen på forrige side";
}
if ($_REQUEST["fisketur"] =="" and $_REQUEST["surf"] =="" and $_REQUEST["skiferie"] =="" and $_REQUEST["fotballtur"] =="")
{
	echo "<br/>Du har ikke fylt ut hvor du vil reise";
}
?>
<h3>Reiseleders personalia</h3>
<form action="bestillingside2.phtml" method="post">
<table>
<tr>
<td>Fornavn:</td><td style="color: red;">*</td>
<td><input type="text" name="fornavn"/></td>
</tr>
<tr>
<td>Etternavn:</td><td style="color: red;">*</td>
<td><input type="text" name="etternavn"/></td>
</tr>
<tr>
<td>Adresse:</td><td style="color: red;">*</td>
<td><input type="text" name="adresse"/></td>
</tr>
<tr>
<td>Postnr:</td><td style="color: red;">*</td>
<td><input type="text" name="postnr" size="2" maxlength="4" /></td>
</tr>
<tr>
<td>Poststed:</td><td style="color: red;">*</td>
<td><input type="text" name="poststed" size="10"/></td>
</tr>
<tr>
<td>Telefonnr:</td><td style="color: red;">*</td>
<td><input type="text" name="tlf" size="10"/></td>
</tr>
<tr>
<td>E-post:</td><td style="color: red;">*</td>
<td><input type="text" name="epost" /></td>
</tr>
<tr>
<td><input type="submit" name="neste" value="Neste" /></td>
</tr>

</table>


</form>

 <?php


$_SESSION["antall"] = $_REQUEST["antall"];
$_SESSION["fisketur"] = $_REQUEST["fisketur"];
$_SESSION["surf"] = $_REQUEST["surf"];
$_SESSION["fotballtur"] = $_REQUEST["fotballtur"];
$_SESSION["skiferie"] = $_REQUEST["skiferie"];
$_SESSION["dag"] = $_REQUEST["dag"];
$_SESSION["dato"] = $_REQUEST["dato"];
$_SESSION["aar"] = $_REQUEST["aar"];
$_SESSION["daghjem"] = $_REQUEST["daghjem"];
$_SESSION["datohjem"] = $_REQUEST["datohjem"];
$_SESSION["aarhjem"] = $_REQUEST["aarhjem"];
$_SESSION["hotellnetter"] = $_REQUEST["hotellnetter"];
 ?>


</div>

</div>

</body>
</html>