<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - England</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="england.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>

<div id="overskriftfotball">
<h2>Fotball i England</h2>
</div>
<img id="pllogo" src="premierleague.jpg" alt="PremierLeague"/>
<img id="pllogo2" src="premierleague.jpg" alt="PremierLeague"/>
<div id="textmidt">

<!--- bildene er hentet fra Wikipedia http://en.wikipedia.org/wiki/File:Old_Trafford_inside_20060726_1.jpg, 
http://en.wikipedia.org/wiki/File:Goodisonview1.JPG -->
<p>Premier League er verden beste liga, med det høyeste tempoet, hardeste taklingene, 
og med de mest lidenskapelige supporterne</p>
<p>iTravel kan tilby deg en komplett pakke, med fly, kampbilletter og hotell, på alle kampene i Premier League.</p>
<p>Vi kan også tilby pakker for kamper i lavere divisjoner i England, så om det er en spesiell kamp du har lyst til å se, er det
bare å sende oss en mail, så skal vi se hva vi får til!</p>
</div>
<br/><br />
<img id="bildevenstre" src="oldtrafford.jpg" alt="Old Trafford" /> 

<img id="bildehoyre" src="goodison.jpg" alt="Everton" /> 
<div id="textundervenstre"><p><em>Old Trafford, i Manchester</em></p></div> 
<div id="textunderhoyre"><p><em>Goodison Park, i Liverpool</em></p></div>
</div>


</div>

</body>
</html>