<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Florida</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>



<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="florida.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="florida.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="florida.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="florida.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="florida.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>



<h2>Fisketur i Florida</h2>
<div id="textmidt">
<p>Florida innehar noen av USAs beste fiskeplasser. Enten du er interessert i å padle langs de uttallige nettverkene av bekker og
 elver eller du heller vil ut på en profesjonell sportsbåt for å hale opp en 100 kilos seilfisk --  Florida har det.  </p>
<p> Floridas vannområder har noen av landets mest attraktive sportsfisker, det inkluderer Redish(uer), Spotted Sea Trout(ikke i ørretfamilien),
 Common Snook og Tarpon. Tusenvis av sportsfiskere kommer hit hvert år for å ta det som kalles en ”Grand Slam”; å ta ett eksemplar av hver av 
 disse fiskene på én dag.  </p> 
<p>Det er muligheter for å bli med profesjonelle sportsfiskere på sine båter ut i Florida Keys. Der leter de etter fisken med profesjonelt 
utstyr og kunnskap og man kan få barracuda, kongemakrell, snapper og til og med den enorme marlin, blant dusinvis av sportsfisker. 
</p>
<p>Florida har også mange muligheter for ferskvannsfiske. Det finnes mange kanaler med massevis av fisk. Du kan enten velge båt og kjøre oppover 
kanalene, stå langs elvebreddene eller bruke en av de mange bryggene og bruene i områdene til å fiske fra. Flere av elvene er berømte for sine 
gode abborplasser.  </p></div>
<img id="bildevenstre" src="floridaboat.jpg" alt="Fiskebåt"/>
<img id="bildehoyre" src="floridaking.jpg" alt="Kingfish" />
<div id="textundervenstre"><p><em>Alt ligger til rette for en stor opplevelse</em></p></div> 
<div id="textunderhoyre"><p><em>Eksotisk fisk venter på å bli dratt opp</em></p></div>


<!--Kilder
http://www.catch-em-all.com
http://www.fishing-florida.com

Bilde:
http://www.catch-em-all.com/boatpic_800.jpg
http://www.catch-em-all.com/imgs/lappinkingsm.jpg-->




</div>

</body>
</html>