<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Hawaii</title>
</head>



<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="hawaii.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="hawaii.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="hawaii.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="hawaii.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="hawaii.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>



<h2>Surfing i Hawaii</h2>
<div id="textmidt">
<p>Hawaii -- surfingens hjemland. Det var her europeere først observerte surfing på 1700-tallet. Siden har surferne valfartet til denne 
paradis-liknende øya i Stillehavet. Hvert år blir det arrangert mange surfe-events her og det er en grunn til at de store surfe-merkene 
som Oakley, Quiksilver og Billabong markedsfører seg hardt i disse konkurransene.  </p>
<p>Det er mange ekstreme surfeplasser på Hawaii, men den mest ekstreme er utvilsomt Banzai Pipeline. Det er verdenskjent blant surfere 
for dets enorme bølger som bryter ned i det grunnere vannet få meter over sylskarpe korallrev. </p> 
<p>Vi kan sette deg i kontakt med mange surfeinstruktører av forskjellig vanskelighetsgrad, men det er nok ingen som
 vil være med deg til Banzai Pipeline! </p></div>
<img id="bildevenstre" src="surfgruppe.jpg" alt="Surfer i Australia"/>
<img id="bildehoyre" src="surfpipe.jpg" alt="Nybegynnerkurs" />
<div id="textundervenstre"><p><em>Knytt bånd med fantastiske folk!</em></p></div> 
<div id="textunderhoyre"><p><em>Banzai Pipeline.. tør du?</em></p></div>


<!--Kilder
http://www.wikipedia.com

Bilde:
http://www.experiencepipeline.com/images/img2.jpg
Privat-->




</div>

</body>
</html>