<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>Pakketurer</title>
</head>

<body background="paradis.jpg">
<div class="bodybox">
<div class="menybox">
<div id="overskrift">
<h1>India!!!!</h1>
</div>
<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="Backpacking" name="back"/></td>
<td><input class="meny" type="submit" value="  Surfing  " name="surf"/></td>
<td><input class="meny" type="submit" value=" Skiferie " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballtur " name="fotball"/></td>
</tr>
</form>


<?php

if (isset($_REQUEST["back"]))
{
	include "nedremeny/back.phtml";
/*if (isset($_REQUEST["back"]))
{
	
}*/
}

if (isset($_REQUEST["surf"]))
{
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>
<p>Her står det masse om oss og bilder og tilbud etc.</p>
</div>


</body>
</html>