<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Italia</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="italia.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="italia.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="italia.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="italia.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="italia.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<h2>Skiferie i Italia</h2>
<div id="textmidt">
<p> I italia kan vi tilby en fantastisk tur til <a href="http://www.dolomitisuperski.com/en-US/ski-holidays-11EN.html">Dolomiti Superski</a>, et enormt skianlegg med 1.220 km løyper som strekker seg over 12 regioner i Italia. </p>
<p>De 450 heisene er knyttet sammen i et frodig fellesskap, planlagt og utviklet gjennom år, knyttet sammen til en lang lenke, eller kanskje vi skal si en gyllen ring. For når solen skinner, og det gjør den ganske ofte her, er Dolomiti Super Ski en storslått ring av heiser og bakker som fører ski- og brettfolket gjennom daler og rundt fjell, på en tur så lang som du nesten bare kan ønske deg. <p>Ett heiskort er nok, det er moderne og elektronisk og puttes i innerlomma og vips! ligger Dolomittene for dine føtter. Forøvrig bør man holde hode og øyne høyt, Dolomittene er blant de mest fascinerende fjellene denne kloden har å by på: forrevne, ville, rødlige i fargen.
 </p>
</div>

<img id="bildevenstre" src="italiasella.jpg" alt="Del av Dolomites Super Ski"/>
<img id="bildehoyre" src="dolomites.jpg" alt="Dolomittene" />
<div id="textundervenstre"><p><em>Del av Dolomites Super Ski</em></p></div> 
<div id="textunderhoyre"><p><em>Dolomittene</em></p></div>


<!--Kilder
http://www.dolomitisuperski.com/en-US/ski-holidays-11EN.html
http://www.aftenposten.no/reise/article1536740.ece

Bilder
http://en.wikipedia.org/wiki/File:Gruppo_del_Sella.JPG
http://en.wikipedia.org/wiki/File:Dolomites_cablecar_view_2009.JPG-->

</div>

</body>
</html>