<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel</title>
</head>

<body background="paradis.jpg">

<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 
<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="index.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<br/><br/>
<p>Om det er noe du lurer på, er  det bare å kontakte oss!</p>
<p>Fyll ut skjemaet under, så svarer vi deg så fort vi kan.</p>
<p>Mvh iTravel</p>
<hr/>



<div id="form">
<p><form action="mailsendt.phtml" method="post">
Navn:<br />
<input type="text" name="navn"/>*<br />
Telefonnummer:<br />
<input type="text" name="telefonnummer"   />*<br />
E-post:<br />
<input type="text" name="epost"  />*<br /><br />
Velg fra listen under, hvilken kategori henvendelsen gjelder.<br /><br /></p>
<tr>
    
    <td><select size="1" name="henvendelse">
            <option>Destinasjoner</option>
            <option>Priser</option>
            <option>Bestilling</option>
            <option>Avbestilling</option>
            <option>Annet</option>
       </select></td>
</tr><br /><br />
<textarea name="beskjed"   cols="30" rows="5">   skriv din kommentar her: </textarea>  <br />
<input type="submit" value="Send" name="knapp"/>
</form>


</div>
</div>

</body>
</html>