<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Lofoten</title>
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="lofoten.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="lofoten.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="lofoten.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="lofoten.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="lofoten.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>



<h2>Fisketur i Lofoten</h2>
<div id="textmidt">
<p>Dette legendariske fiskestedet med sin særegne natur er et Mekka for sportsfiskeren. Her kan man sette personlige rekorder
 i hopetall omgitt av fantastiske naturomgivelser som man virkelig bare må oppleve.  </p>
<p> Torskefisket, eller ”Skreifisket” som det heter, starter i januar og varer fram til april Dette er perioden da torsken kommer
 opp til overflaten og inn til kysten for å gyte. Denne fisken er veldig sprek og svært underholdende å hale inn. Stivere stenger 
 enn 30 lbs anbefales ikke fordi da kan man fort miste følelsen med fisken og risikere å miste den.  </p> 
<p>Når torskefisket stopper i slutten av april, starter vårfisket. Da er det hyse, brosme og steinbit som er i søkelyset.
 Dette fisket varer over hele sommeren. Rundt 15. juli starter det mange anser som det mest fantastiske fisket: Storseifisket.
 Sei over 15 kg er slettes ikke uvanlig og man skal være i god form for å klare å dra opp en slik sei. Ihvertfall så blir man det etterpå! 
</p>
<p>Storfisken kommer inn mot kysten for å frotse etter småsild på natten, og da kan det fort være godt å være sportsfisker i solnedgangen 
 i Lofoten, omgitt av de særegne spisse fjellene.   </p></div>
<img id="bildevenstre" src="lofotskrei.jpg" alt="Lofotfiske"/>
<img id="bildehoyre" src="fjellogbat.jpg" alt="Sjøen og fjellet" />
<div id="textundervenstre"><p><em>Lofotfiske på sitt beste</em></p></div> 
<div id="textunderhoyre"><p><em>Flott natur og båten full av fisk</em></p></div>


<!--Kilder
http://www.lofoten-startside.no/fiske.htm
http://no.wikipedia.org/wiki/Lofotfiske

Bilde:
http://www.lofoten-rorbuferie.no/foto/grupper/images/g03011.jpg
http://www.lofoten-rorbuferie.no/foto/havet/images/0130203.jpg-->




</div>

</body>
</html>