<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.html" >Om oss</a></li> 
<li><a href="kontakt.html" >Kontakt oss</a></li>
<li><a href="reisevilkar.html" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<form action="" method="get">
<table id="menytabell">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>



<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="index.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="index.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</form>
</div>


<br/><br/>
<?php




if(isset($_REQUEST["knapp"]))
if (($_REQUEST["navn"]=="")or($_REQUEST["telefonnummer"]=="")
or($_REQUEST["epost"]==""))
{
    echo "<strong>Du må fylle ut alle feltene merket med * <br/></br/> </strong>";
    echo "<br/><br/>";
    echo "<a href='kontakt.phtml'>Tilbake</a>";
}   
else 
    
{
    mail("gruppe28@hotmail.com", "$_REQUEST[henvendelse]","$_REQUEST[beskjed]\r\n$_REQUEST[navn]\r\n$_REQUEST[telefonnummer]","From: $_REQUEST[epost]");         

echo "<br/><br/><b>Du har sendt inn følgende informasjon;</b><br/><br/>";
echo "<b>Navn: </b>". $_REQUEST["navn"]. "<br/><br>";
echo "<b>Telefonnummer:</b> ". $_REQUEST["telefonnummer"]. "<br/><br/>";
echo "<b>E-postadresse:</b> ". $_REQUEST["epost"]. "<br/><br/>";
echo "<b>Temaet henvendelsen gjelder:</b><br/> ". $_REQUEST["henvendelse"]. "<br/><br/>";
echo "<b>Din kommentar: </b><br/> ". $_REQUEST["beskjed"]. "<br/><br/>";



echo "<a href='index.phtml'>Klikk her for å gå tilbake til forsiden.</a>";
}
?>

</div>

</body>
</html>
