<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Om oss</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>



<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 
<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="omoss.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="omoss.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="omoss.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="omoss.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="omoss.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<br/><br/>
<div id="omoss">
<p>iTravel er et reiseselskap som ble etablert høsten 2010.</p>
<p>Vårt mål er å kunne tilby den reiselystnegode tilbud til forskjellige destinasjoner verden rundt.
Vi har gode avtaler med flyselskap og kvalitetshotell verden over, slik at vi kan tilby gode pakkeløsninger.
Vårt mål er å bli ledende innen opplevelsesreiser, og vi prøver også hele tiden å være pris- og konkurransedyktige.
Vi satser også på å ha en god kundeservice ved eventuelle spørsmål eller problemer tilknyttet reisen eller bestillingen.</p>
</div>
<h3>God tur!</h3>


</div>

</body>
</html>