<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Reisevilkår</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 
<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="reisevilkar.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="reisevilkar.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="reisevilkar.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="reisevilkar.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="reisevilkar.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<br/><br/>
<div id="reisevilkar">
<h3>iTravel fraskriver seg alt ansvar om:</h3>
<ul><li>Bagasjen blir borte under reisen.</li></ul>
<ul><li>Flyet er forsinket, så overgangsfly har dratt ved ankomst.</li></ul>
<ul><li>Flyet blir kansellert.</li></ul>
<ul><li>Flyet er overbooket, og du/dere ikke kommer med som avtalt.</li></ul>
<ul><li>Den/De reisendes helse/tilstand gjør at de ikke er skikket til å gå ombord på flyet.</li></ul>
<ul><li>Om det bestilte hotellet er fullbooket ved ankomst.</li></ul>
<br />
<h3>Ved bestilling av tur på nett gjelder følgende regler/priser:</h3>
<ul><li>Ved bestilling på nett, forekommer det et miljøgebyr på 120kr.</li></ul>
<ul><li>Ved betaling med kort, kommer tilleggsgebyr på 3% av reisens totale kostnad.</li></ul>
<ul><li>Avbestilling må senest gjennomføres 1 måned før avtalt reisedato, og kun opptil 80% av totalsummen vil bli refundert. </li></ul>
<ul><li>Ved helgetilbud/supertilbud gjelder ikke avbestillingsgarantien.</li></ul>
<ul><li>Ved bestilling booker vi deg inn på det samarbeidshotellet som er mest gunstig i forhold til destinasjon og ønsket pris.</li></ul>
<br />
<h3>Husk at det er til envher tid hvert enkelt flyselskap sine regler som gjelder ved transport!</h3>
</div>

</div>

</body>
</html>