<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
<link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />

</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf2"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="send.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="send.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf2"]))
{
     $_SESSION["filnavn"]="send.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="send.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="send.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<br/><br/>
<p>Er du lei av allminnelige reisemål der du bare ligger og kjeder deg på stranda hele ferien? 
Ønsker du å gjøre noe nytt i ferien? iTravel arrangerer reiser for den mer eventyrlystne som ønsker
 å oppleve mer i ferien. Velkommen til iTravel - vi er her for deg!</p>
<img id="balisurf" src="balisurf.png" alt="bali" />



<div id="bestilling">
<?php
session_start();
?>
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Sendt</title>
</head>
<?php


Mail ("gruppe28@hotmail.com","Bestilling","Navn: ".$_SESSION["fornavn"]." ".$_SESSION["etternavn"]."\r\n".
	  "Tur: ".$_SESSION["fisketur"].$_SESSION["surf"].$_SESSION["fotballtur"].$_SESSION["skiferie"]."\r\n".
	  "Utreise: ".$_SESSION["dag"]."/".$_SESSION["dato"]."/".$_SESSION["aar"]."\r\n".
	  "Hjemreise: ".$_SESSION["daghjem"]."/".$_SESSION["datohjem"]."/".$_SESSION["aarhjem"]."\r\n".
	  "Hotellnetter: ".$_SESSION["hotellnetter"]."\r\n".
	  "Antall: ".$_SESSION["antall"]."\r\n".
	  "Adresse: ".$_SESSION["adresse"]." ".$_SESSION["postnr"]." ".$_SESSION["poststed"]."\r\n".
	  "Tlf: ".$_SESSION["tlf"]."\r\n".
	  "Epost: ".$_SESSION["epost"]."\r\n".
	  "Pris: ".$_SESSION["pris"],"From: ".$_SESSION["epost"]);

?>
<p>Takk <?php echo $_SESSION["fornavn"] ?>. Din bestilling har blitt sendt til oss. Klikk <a href="index.phtml">her</a> 
	for å gå tilbake til forsiden.</p>

<body>
</body>
</html>
</div>

</div>

</body>
</html>