<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Spania</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="england.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="england.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>

<div id="overskriftfotball">
<h2>Fotball i Spania</h2>
</div>
<img id="laliga" src="laliga.jpg" alt="La Liga"/>
<img id="laliga2" src="laliga.jpg" alt="La Liga"/>
<!--Bildene er hentet fra Wikipedia http://en.wikipedia.org/wiki/File:Camp_nou_2.jpg, 
http://en.wikipedia.org/wiki/File:Santiagobernabeupanoramav3.jpg-->
<div id="textmidt">

<p>La Liga er ligaen for deg som liker den tekniske delen av fotballen. I Spania er man opptatt av at fotballen skal være en
vakker idrett, og dette bærer ligaen preg av. Barcelona og Real Madrid er to av verdens aller beste lag, med hjemmebaner som
 kan ta over 70000 mennesker.</p> <p>Atmosfæren på disse banene må bare oppleves!</p>
<p>iTravel kan tilby deg en total pakke, med fly, kampbilletter, og hotell, på alle kampene i La Liga.</p>
</div>
<br/><br />
<img id="bildevenstre" src="campnou.jpg" alt="Camp Nou" /> 

<img id="bildehoyre" src="santiago.jpg" alt="Real Madrid" /> 
<div id="textundervenstre"><p><em>Camp Nou, i Barcelona</em></p></div> 
<div id="textunderhoyre"><p><em>Santiago Bernabéu, i Madrid</em></p></div>
</div>


</div>

</body>
</html>