<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - Sveits</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="sveits.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="sveits.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="sveits.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="sveits.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="sveits.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>



<h2>Skiferie i Sveits</h2>
<div id="textmidt">
<p>Med sin plassering midt i Alpene er Sveits et skisportens Mekka. Det finnes ca 150 skiområder, 
hvorav de mest kjente er La Tzoumaz, Verbier og St. Moritz. Her finner du hyggelige fjellandsbyer, 
fantastiske panorama utsikter, og ikke minst utrolig gjestfrie mennesker. I tillegg er forholdene for 
skiløpere og snowboardere meget bra.</p>
<p>Om du har en eventyrer i deg så kan du prøve deg på Haute Route, en tur som går mellom Chamonix og
 Mount Blanc i Frankrike til Matterhorn som ruver over Zermatt i Sveits. Turen tar ca. en uke på ski
  og er 180 km lang. Det er muligheter til å variere hvor du vil starte fra og hvilken rute du vil ta.</p> 
<p>Dette er for dem som virkelig har lyst på en utfordring, da mange starter turen, men ikke alle gjør den ferdig.
 Men det viktigste er jo at man har prøvd, og at man har hatt en fantastisk ferie litt utenom det vanlige!
</p>
<p>For deg med familie eller om du reiser alene vil vi anbefale <a href="http://www.hotelalphubel.ch/w_fe_1.htm">Waldesruh Hotel</a> i
 Saas-Fee som ligger kun 4.3 km fra Allalinhorn.</p>
<p>Du kan være 100 % sikker på at du får valuta for pengene i Sveits.
 Gjestfriheten, maten og standarden på 
alpinbakkene er i særklasse!</p></div>
<img id="bildevenstre" src="sveitsa.jpg" alt="Sveits Allalinhorn"/>
<img id="bildehoyre" src="sveitsh.jpg" alt="Sveits Hauteroute" />
<div id="textundervenstre"><p><em>Sveits Allalinhorn</em></p></div> 
<div id="textunderhoyre"><p><em>Sveits Haute Route</em></p></div>


<!--Kilder
http://www.skiinfo.no/Land/Sveits-ECH-9671-no.jhtml
http://en.wikipedia.org/wiki/Haute_Route

Bilde:
http://en.wikipedia.org/wiki/File:Allalinhorn_4027_2007_04_17.JPG
http://en.wikipedia.org/wiki/File:Hauteroute.jpg-->




</div>

</body>
</html>