<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="css1.css"/>
	

	<title>iTravel - USA</title>
        <link rel="icon" href="logo.jpg" type="image/x-icon" />
         <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>



<div id="overbodybox">
<ul><li><a href="omoss.phtml" >Om oss</a></li> 
<li><a href="kontakt.phtml" >Kontakt oss</a></li>
<li><a href="reisevilkar.phtml" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<img id="itravel" src="headbox.png" alt="Head"   /> 

<table id="menytabell">
<form action="" method="get">
<tr>
<td><input class="meny" type="submit" value="    Hjem    " name="hjem"/></td>
<td><input class="meny" type="submit" value="  Fisketurer  " name="fisk"/></td>
<td><input class="meny" type="submit" value="   Surfing   " name="surf"/></td>
<td><input class="meny" type="submit" value="  Skiferier  " name="ski"/></td>
<td><input class="meny" type="submit" value="Fotballturer " name="fotball"/></td>
</tr>
</form>


<?php
if (isset($_REQUEST["hjem"]))
{
	$_SESSION["filnavn"]="usa.phtml";
    	include "nedremeny/hjem.phtml";
}

if (isset($_REQUEST["fisk"]))
{
    $_SESSION["filnavn"]="usa.phtml";
	include "nedremeny/fisk.phtml";

}

if (isset($_REQUEST["surf"]))
{
     $_SESSION["filnavn"]="usa.phtml";
	include "nedremeny/surf.phtml";
}
if (isset($_REQUEST["ski"]))
{
     $_SESSION["filnavn"]="usa.phtml";
	include "nedremeny/ski.phtml";
}
if (isset($_REQUEST["fotball"]))
{
    $_SESSION["filnavn"]="usa.phtml";
	include "nedremeny/fotball.phtml";
}
?>
</table>
</div>


<h2>Skiferie i USA</h2>
<div id="textmidt">
<p>I USA har vi tre spennende destinasjoner, alle fantastiske ski anlegg for både de unge og gamle, så ta med hele familien på en fantastisk ferie og kos dere i Breckenridge i Colorado, Deer Valley i Utah eller kanskje det frister med spennende Anchorage i Alaska? Uansett er vi sikre på at du vil du få oppleve fantastiske ski anlegg med utmerket service.</p>
<h4>Deer Valley, Utah</h4>
<p>Deer Valley ligger i den historiske gruvebyen Park City i Utah, ca 5 mil fra Salt Lake City flyplass. De ble kåret til det beste ski anlegget i Nord-Amerika av leserene i SKI Magazine imponerende tre år på rad – 2008, 2009 og igjen i 2010.  Vi vil anbefale overnatting på <a href="http://www.steinlodge.com/lodge">Stein Eriksen Lodge</a>, et flott hotell for de som vil ha litt luksus. For de som er mest ute etter nærhet til bakken og noe litt billigere er <a href="http://www.deervalley.com/lodging.html">Deer Valley Resort Lodging</a> å anbefale.</p>
<h4>Breckenridge, Colorado</h4>
<p>Breckenridge har vært det mest populære ski anlegget i Nord-Amerika de siste åra. I 2007 – 2008 kunne de skryte av 1,63 millioner besøkende, noe som gjør de til det mest populære reisemålet i Nord-Amerika. Anlegget kan skimte med 155 løyper, så om du ser fram til en dag fri fra løypene eller om du leter etter litt alternativt eventyr, så har Breckenridge like mye å tilby utenfor løypene som i løypene. </p>
<h4>Alyeska, Alaska</h4>
<p>Alpin kjøring I Alaska er sinnsykt; høye fjelltopper som er på same nivå som havet gjør at Alaska har noe av de beste forholdene som Moder Natur kan tilby. Ski kjørere og snowboardere har flere valg for å kjøre alpint 45 minutter fra sentrum av Anchorage – alle med fantastisk utsikt og det beste terrenget du kan finne. Vi vil anbefale Alyeska Ski Resort, en fantastisk park der du har alt du trenger, inkludert overnatting på <a href="http://www.alyeskaresort.com/hotel/index.aspx">Hotel Alyeska</a>.</p></div>
<img id="bildevenstre" src="breckenridge.jpg" alt="Breckenridge"/>
<img id="bildehoyre" src="deervalley.jpg" alt="Deer Valley Ski Resort" />
<div id="textundervenstre"><p><em>Breckenridge, en av de mange toppene</em></p></div> 
<div id="textunderhoyre"><p><em>Deer Valley Ski Resort</em></p></div>

<!--Kilder
http://www.forbes.com/2001/11/08/1108feat_5.html
http://www.deervalley.com/
http://www.deervalley.com/lodging.html

http://www.steinlodge.com/lodge
http://www.breckenridge.com/
http://en.wikipedia.org/wiki/Breckenridge_Ski_Resort

http://www.anchorage.net/772.cfm
http://www.alyeskaresort.com/
http://www.alyeskaresort.com/hotel/index.aspx


Bilde:
http://en.wikipedia.org/wiki/File:Imperial_ridge.jpg
http://en.wikipedia.org/wiki/File:Deervalleyutah_0209.jpg-->

</div>

</body>
</html>