<?php
session_start();
?>
<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
	<meta name="description" content="Hovedside - reiseside."/>
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen"/>
	<link rel="stylesheet" href="cssiPad.css"/>
	

	<title>iTravel</title>
    <link rel="icon" href="logo.jpg" type="image/x-icon" />
        <link rel="shortcut icon" href="logo.jpg" type="image/x-icon" />
</head>
<body>


<div id="overbodybox">
<ul><li><a href="omossiPad.html" >Om oss</a></li> 
<li><a href="kontaktiPad.html" >Kontakt oss</a></li>
<li><a href="reisevilkariPad.html" >Reisevilkår</a></li>
</ul>
</div>


<div class="bodybox">
<div class="menybox">
<div id="itraveloverskrift"><h1>iTravel</h1></div>

<div id="meny">
<ul>
<li><a href="indexiPad.phtml" style="background: white;">Hjem</a></li>
</ul>
<ul>
<li><a href="#" style="background: white;">Fisketurer</a>
<ul>
<li><a href="lofoteniPad.html" style="background: white;">Lofoten</a></li>
<li><a href="floridaiPad.html" style="background: white;">Florida</a></li>
<li><a href="australiafiskiPad.html" style="background: white;">Australia</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#" style="background: white;">Surfing</a>
<ul>
<li><a href="baliiPad.html" style="background: white;">Bali</a></li>
<li><a href="australiaiPad.html" style="background: white;">Australia</a></li>
<li><a href="hawaiiiPad.html" style="background: white;">Hawaii</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#" style="background: white;">Skiferie</a>
<ul>
<li><a href="sveitsiPad.html" style="background: white;">Sveits</a></li>
<li><a href="usaiPad.html" style="background: white;">USA</a></li>
<li><a href="italiaiPad.html" style="background: white;">Italia</a></li>
</ul>
</li>
</ul>
<ul>
<li><a href="#" style="background: white;">Fotballtur</a>
<ul>
<li><a href="englandiPad.html" style="background: white;">England</a></li>
<li><a href="spaniaiPad.html" style="background: white;">Spania</a></li>
<li><a href="argentinaiPad.html" style="background: white;">Argentina</a></li>
</ul>
</li>
</ul>

</div>
</div>

<br /><br />
<?php


if(isset($_REQUEST["knapp"]))
if (($_REQUEST["navn"]=="")or($_REQUEST["telefonnummer"]=="")
or($_REQUEST["epost"]==""))
{
    echo "<strong>Du må fylle ut alle feltene merket med *  </strong>";
?>
<br /><br />
<?php
    
    echo "<a href='kontaktiPad.html'>Tilbake</a>";
}   
else 
    
{
    mail("gruppe28@hotmail.com", "$_REQUEST[henvendelse]","$_REQUEST[beskjed]\r\n$_REQUEST[navn]\r\n$_REQUEST[telefonnummer]","From: $_REQUEST[epost]");         

echo "<br/><br/><b>Du har sendt inn følgende informasjon;</b><br/><br/>";
echo "<b>Navn: </b>". $_REQUEST["navn"]. "<br/><br>";
echo "<b>Telefonnummer:</b> ". $_REQUEST["telefonnummer"]. "<br/><br/>";
echo "<b>E-postadresse:</b> ". $_REQUEST["epost"]. "<br/><br/>";
echo "<b>Temaet henvendelsen gjelder:</b><br/> ". $_REQUEST["henvendelse"]. "<br/><br/>";
echo "<b>Din kommentar: </b><br/> ". $_REQUEST["beskjed"]. "<br/><br/>";



echo "<a href='indexiPad.phtml'>Klikk her for å gå tilbake til forsiden.</a>";
}
?>
</div>


</body>
</html>
