<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<meta name="description" content="Leveranse 1 i Web-Prosjekt.">
	<meta name="author" content="Barbro M. Klashaugen, Marius Karlsen, Dan Eig, Alexander Paulsen">
	<link rel="stylesheet" href="css.css">
	
		<title>Webprosjekt Gruppe 28</title>
		
</head>
<body>
<div id="header">
	<h1> Gruppeside for gruppe 28</h1>
	<div class="menu">
	<ul>
		<li> <a href="hjemmesider.html">Hjem</a></li>
	<li> <a href="prosjektbeskrivelse.html">Prosjektbeskrivelse</a></li>
	<li> <a href="planer.html" >Planer</a></li>
	<li> <a href="avtalekart.html">Avtale og kart</a></li>
	<li> <a href="moter.html">Prosjektdagbok</a></li>
	<li> <a href="midtveisrapport.html">Midtveisrapport</a></li>
	<li> <a href="skisse.html">Sluttrapport</a></li>
	<li> <a href="forum.phtml" style="background:black;">Forum</a></li>
	</ul>
	</div>
	</div>
<div id="bodybox">
<h2 style="text-align:center;">Forum</h2>
<hr/>
<?php

$forum = file("forum.txt");
rsort($forum);
echo "Siste melding ble ".$forum[1]."<br/>";


if (($_REQUEST["passord"] == "webprosjekt123") and ($_REQUEST["navn"] == "Marius Karlsen" or $_REQUEST["navn"] == "Barbro Klashaugen"
	or $_REQUEST["navn"] == "Dan Eig" or $_REQUEST["navn"] == "Alexander Paulsen"))
	{
		$dato = date("d/m/Y H:i");
		$filref = fopen ("forum.txt", "a");
		fwrite ($filref, "\r\n"."Postet: ".$dato."\r\n"."Navn: ".$_REQUEST["navn"]."\r\n"."Melding: ".$_REQUEST["melding"]."\r\n");
		fclose($filref);
	}


$forum = file("forum.txt");

for ($i = 0; $i < count($forum); $i++)
{
	echo $forum[$i]."<br/>";
}
?>
<hr/>
<form action="" method="post">
<table>
<tr>
<td>Navn:</td>
<td>Passord:</td>
</tr>
<tr>
<td><select size="1" name="navn">
	<option></option>
	<option value="Marius Karlsen">Marius Karlsen</option>
    <option value="Barbro Klashaugen">Barbro Klashaugen</option>
    <option value="Dan Eig">Dan Eig</option>
    <option value="Alexander Paulsen">Alexander Paulsen</option>
    </select>
</td>
<td><input type="password" name="passord" value="webprosjekt"></td>
</tr>
</table>
<table>
<tr>
<td>Melding</td>
</tr>
<tr>
<td><textarea cols="34" rows="5" name="melding"></textarea></td>
</tr>
<tr>
<td><input type="submit" value="Post" name="post" /></td>
</tr>
</table>
</form>

 



<div class="footer">
	<hr/>
	<p>Siden er laget av og oppdateres av gruppe 28.</p>
	<a href="http://validator.w3.org/check/referer">
	<img src="http://www.stud.hio.no/~s171677/validlogo.png" alt="Valider HTML"/>
	</a>
	<a href="http://jigsaw.w3.org/css-validator/check/referer">
	<img src="http://jigsaw.w3.org/css-validator/images/vcss-blue" alt="Valider CSS"/>
	</a>
</div>
</div>
</body>	
</html>