<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Backpacking</title>
</head>

<body>
<tr>
			<td><form action='india.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='India' name='india'/></form></td>
		</tr>
		<tr>
			<td><form action='pakistan.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Pakistan' name='pakistan'/></form></td>
		</tr>
		<tr>
			<td><form action='peru.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Peru' name='peru'/></form></td>
		</tr>
</body>
</html>