<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Fisketur</title>
</head>

<body>
<tr>
			<td><form action='lofoten.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Lofoten' name='lofoten'/></form></td>
		</tr>
		<tr>
			<td><form action='florida.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Florida' name='florida'/></form></td>
		</tr>
		<tr>
			<td><form action='australiafisk.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Australia' name='australia'/></form></td>
		</tr>
		<tr>
			<td><form action="<?php echo $_SESSION['filnavn']; ?>" method='get'/>
				<input class='lukk' type='submit' value='Lukk' name='lukk'/></form></td>
		</tr>
</body>
</html>