<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Fotballtur</title>
</head>

<body>
<tr><td> </td><td></td><td></td><td> </td>
			<td><form action='england.phtml' method='get'>
				<input class='nedremeny' type='submit' value='England' name='england'/></form></td>
		</tr>
		<tr><td> </td><td></td><td></td><td> </td>
			<td><form action='spania.phtml' method='get'>
				<input class='nedremeny' type='submit' value='Spania' name='spania'/></form></td>
		</tr>
		<tr><td> </td><td></td><td></td><td> </td>
			<td><form action='argentina.phtml' method='get'>
				<input class='nedremeny' type='submit' value='Argentina' name='argentina'/></form></td>
		</tr>
		<tr><td> </td><td> </td><td> </td><td> </td>
			<td><form action="<?php echo $_SESSION['filnavn']; ?>" method='get'>
				<input class="lukk" type='submit' value='Lukk' name='lukk'/></form></td>
		</tr>
</body>
</html>