<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Hjem</title>
</head>

<body>
<tr>
			<td><form action='index.phtml' method='get'>
				<input class='nedremeny' type='submit' value='Gå hjem' name='hjemover'/></form></td>
</tr>
<tr>
			<td><form action="<?php echo $_SESSION['filnavn']; ?>" method='get'>
				<input class="lukk" type='submit' value='Lukk' name='lukk'/></form></td>
		</tr>

</body>
</html>