<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Skiferie</title>
</head>

<body>
<tr><td> </td><td></td>
			<td><form action='sveits.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Sveits' name='Sveits'/></form></td>
		</tr>
		<tr><td> </td><td></td>
			<td><form action='usa.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='USA' name='usa'/></form></td>
		</tr>
		<tr><td> </td><td></td>
			<td><form action='canada.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Canada' name='canada'/></form></td>
		</tr>
		<tr><td> </td><td> </td>
			<td><form action='index.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Lukk' name='lukk'/></form></td>
		</tr>
</body>
</html>