<?php
session_start();
?>
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<title>Surf</title>
</head>

<body>
<tr><td> </td><td> </td>
			<td><form action='bali.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Bali' name='bali'/></form></td>
		</tr>
		<tr><td> </td><td> </td>
			<td><form action='australia.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Australia' name='australia'/></form></td>
		</tr>
		<tr><td> </td><td> </td>
			<td><form action='hawaii.phtml' method='get'/>
				<input class='nedremeny' type='submit' value='Hawaii' name='hawaii'/></form></td>
		</tr>
		<tr><td> </td><td> </td>
			<td><form action="<?php echo $_SESSION['filnavn']; ?>" method='get'/>
				<input class="lukk" type='submit' value='Lukk' name='lukk'/></form></td>
		</tr>
</body>
</html>